In [12]:
x = input("Input:")

#input(1a3432)


for i in x: #x = 1a3432
    if i.isnumeric():
        i = int(i)
        for j in range(i): #1a3432
                j = int(j)
                if (j) % 3 == 2 : #1 2 3 4 5 6
                    print("#",end="")
                else:
                    print("*",end="")
    print()
    """elif i.isalpha() or i == 0:
        print()"""

**
**#
**#*


In [14]:
a = input("Enter your running pace (minutes per kilometer): ").split(":")
b = input("Enter your distance (a) Mini-marathon, (b) Half-marathon, (c) Full-marathon: ")


a[0] = int(a[0])
a[1] = int(a[1])

x = a[0] *60

<class 'list'>


In [18]:
x = 5

for i in range(x):
    for j in range(x):
        if i == j:
            print("$",end="")
        else:
            print("&", end="")
    print()

$&&&&
&$&&&
&&$&&
&&&$&
&&&&$


In [20]:
x = input("")
a = int(input("size"))
b = int(input("pattern 1 or 2"))

for i in range(a):
    for j in range(a):
        if b == 1:
            if i == j:
                print("%s"%x,end="")
            else:
                print(".", end="")
        elif b == 2:
            if j == a-i-1:
                print("%s"%x, end="")
            else:
                print(".", end="")
    print()


....#
...#.
..#..
.#...
#....


In [35]:
x=int(10)
for i in range(1,x+1):
    print(" "*((x-i)), end="")
    print("#"*i)

    #print(" "*((x-i)))

         #
        ##
       ###
      ####
     #####
    ######
   #######
  ########
 #########
##########


In [6]:
x=10
for i in range(1,x+1):
    print("#"*i,end="")
    print(" "*2*(x-i),end="")
    print("#"*i)
for i in range(x-1,0,-1):
    print("#"*i,end="")
    print(" "*2*(x-i),end="")
    print("#"*i)


#                  #
##                ##
###              ###
####            ####
#####          #####
######        ######
#######      #######
########    ########
#########  #########
####################
#########  #########
########    ########
#######      #######
######        ######
#####          #####
####            ####
###              ###
##                ##
#                  #


In [7]:
x= int(input(""))
for i in range(1,x+1):
    for j in range(1,x+1):
        if j<=i:
            if j%2==0:
                print("#",end="")
            else:
                print("*",end="")
    print(" "*(2*(x-i)), end="")
    for j in range(1,x+1):
        if j<=i:
            if j%2==0:
                print("#",end="")
            else:
                print("*",end="")
    print()

for i in range(x-2,0,-1):
    for j in range(1,x+1):
        if j<=i:
            if j%2==0:
                print("#",end="")
            else:
                print("*",end="")
    print(" "*(2*(x-i)), end="")
    for j in range(1,x+1):
        if j<=i:
            if j%2==0:
                print("#",end="")
            else:
                print("*",end="")
    print()
#ผีเสื้อ
    


*        *
*#      *#
*#*    *#*
*#*#  *#*#
*#*#**#*#*
*#*    *#*
*#      *#
*        *


In [87]:
from math import pi

x = pi

print("%f" %x) #3 3 3.14

3.141593


In [102]:
x = input("DNA")
a = input("Base")
c = ""
t = True

o = "otop"

for i in x:
    if i == a:
        c += ("%s" %o)
    
  
for j in x:
    print("c: %s" %j)
    if t:
        print("True if test")
print(c)


c: A
True if test
c: T
True if test
c: G
True if test
c: G
True if test
c: C
True if test
c: A
True if test
c: T
True if test
c: T
True if test
c: A
True if test
otopotopotop 

In [ ]:
a,b = x = input("Please enter your information: ").split(",")

if a.isnumeric() and b.isalpha() or a.isalpha() and b.isnumeric():
    if a.isnumeric() and b.isalpha():
        a = int(a)
        if a >=0 and a<=120:
            print("Your name is %s" %b)
            print("Your age is %s" %a)
        else:
            print("Please enter your complete information.")
    elif a.isalpha() and b.isnumeric():
        b = int(b)
        if b >=0 and b<=120:
            print("Your name is %s" %a)
            print("Your age is %s" %b)
        else:
            print("Please enter your complete information.")
else:
    print("Please enter your complete information.")

In [89]:
import random

w = input("Rectangle width")
h = input("Rectangle height: ")
b = input("Border thickness: ")

w = int(w)
h = int(h)
b = int(b)

for i in range(h):
    for j in range(w):
        if j < b or j >= w-b or i < b or i >= h-b:
            r = random.randint(0,2)
            if r == 0:
                print("#", end="")
            elif r == 1:
                print("*", end="")
            elif r == 2:
                print("$", end="")
        else:
            print(" ", end="")
    print()
# 4 เหลี่ยมมีรู


#*$##$#*#**#$*$##$#*
$$#*#$*$$*#$##*$#*$$
$*$$$*#**$$$**$*###*
$$$#*#*$$$$#*$*#*#**
***$            ##$#
*$*$#***$*$$*$***#*$
##$*$$$##*#*#**#$$$*
#$$$$#$*##$$*$#*$*$*
*##*$$*#*##$*$$##*$$


In [6]:
from operator import itemgetter

coffeeDB = [['A','Americano',120],['M','Matcha Latte',125],['C','Signature Chocolate',130],['E','Espresso',50],['O','Sai Nam Pueng Orange Juice',95],['R','Iced Raspberry Juice Tea',115]]

#### Task 1: Utilize the sorted() function to create a new variable sorted in descending order by price, which can be utilized for printing.
menusorted = sorted(coffeeDB, key=itemgetter(2), reverse=True)

print("Beverage Menu")
print("-"*56)
print("| %-3s | %-4s | %-30s | %-6s |" % ("No.","Code","Item Name","Price"))
print("-"*56)
for i, val in enumerate(menusorted):
    print("| %2d. | %-4s | %-30s | %6.2f |" % (int(i+1),val[0],val[1],val[2]))
print("-"*56)

menucode = [i[0] for i in coffeeDB]

userorder = input("User's orders: ")

summ_item = []
for a in userorder:
    if a.upper() in menucode:

        #check exist

        found = -1
        for i, b in enumerate(summ_item):
            if b[0] == a.upper():
                found = i 

        #### CODE HERE ####
        if found >= 0:
            summ_item[found][1] += 1
        elif found < 0:
            summ_item.append([a.upper(), 1])
        """else:
            print("skipping NOCODE (%s)" % a)"""

if len(summ_item) > 0:
    print("Bill summary")
    print("-"*56)
    print("| %-3s | %-30s | %-4s | %-6s |" % ("NO.","ITEM NAME","QTY","AMOUNT"))
    print("-"*56)
    total = 0
    for i, val in enumerate(summ_item):

        menudetail = [[d[1],d[2]] for d in coffeeDB if val[0] == d[0]]

        #### Task 3: Complete the calculation for "menuprice", "qty", and "total".
        #### CODE HERE ####

        menuprice = menudetail[0][1]
        qty = val[1]
        amount = menuprice * qty
        total += amount

        print("| %2d. | %-30s | %-4s | %6.2f |" % (i+1, menudetail[0][0], qty, amount))
    print("-"*56)

    #### Task 4: Conclude the summary at the end of the bill with a VAT rate of 7%.
    #### CODE HERE ####

    subtotal = total
    tax = subtotal * 0.07
    grand_total = subtotal + tax

    print("| %-43s | %6.2f |" % ("Subtotal", subtotal))
    print("| %-43s | %6.2f |" % ("Total tax", tax))
    print("| %-43s | %6.2f |" % ("Total", grand_total))
    print("-"*56)
else:
    print("NO ORDER!!!")


Beverage Menu
--------------------------------------------------------
| No. | Code | Item Name                      | Price  |
--------------------------------------------------------
|  1. | C    | Signature Chocolate            | 130.00 |
|  2. | M    | Matcha Latte                   | 125.00 |
|  3. | A    | Americano                      | 120.00 |
|  4. | R    | Iced Raspberry Juice Tea       | 115.00 |
|  5. | O    | Sai Nam Pueng Orange Juice     |  95.00 |
|  6. | E    | Espresso                       |  50.00 |
--------------------------------------------------------
Bill summary
--------------------------------------------------------
| NO. | ITEM NAME                      | QTY  | AMOUNT |
--------------------------------------------------------
|  1. | Signature Chocolate            | 1    | 130.00 |
|  2. | Matcha Latte                   | 1    | 125.00 |
|  3. | Espresso                       | 2    | 100.00 |
|  4. | Americano                      | 1    | 120.00 |
|  5

In [5]:
summ_item[found][1]

3

In [4]:
print(float(0.0001))

0.0001


In [1]:
max(5,4,5,1,2,3)

5

In [2]:
x = input("Input: ").split()
print(x)

['SIIT']


In [3]:
x = input("Input: ").split()
d = {}

# Count the frequency of each word in a case-insensitive manner
for i in x:
    i = i.lower()  # Convert to lowercase to ensure case insensitivity
    if i in d:
        d[i] += 1
    else:
        d[i] = 1

# Find the maximum frequency
max_freq = max(d.values())

# Print the word(s) with the highest frequency
for word, freq in d.items():
    if freq == max_freq:
        print(word, "=", freq)


ant = 2
bat = 2


SyntaxError: cannot assign to True (3681160204.py, line 1)

In [1]:
def w(n,p="SIIT"):
    print("Hi,", n+"!", "W to", p+".")

In [2]:
w("Sheldon")

Hi, Sheldon! W to SIIT.


In [3]:
w("Sdasd", "Dasdsadds")

Hi, Sdasd! W to Dasdsadds.


In [4]:
def f1():
    global x
    x = 10
def f2():
    x =20

In [6]:
x=15
print(x)


15
15


In [7]:
f1()
print(x)

15


In [1]:
l=[]

In [2]:
l.append(20)

In [3]:
l

[20]

In [4]:
xList = []

def UserInput():
    while True:
        x = input("Enter an input: ")
        if x == "Done":
            break
        else:
            try:
                x = int(x)
                if x < 0:
                    print("Error")
                else:
                    xList.append(x)
            except ValueError:
                print("Error")
    return xList
            
def SumOut(xList):
    return sum(xList)

def MinOut(xList):
    return min(xList)

def MaxOut(xList):
    return max(xList)

# Call the UserInput function to get the input list
UserInput()

# Check if xList has any valid entries before printing the results
if xList:
    print("The summation is %d" % SumOut(xList))
    print("The minimum is %d" % MinOut(xList))
    print("The maximum is %d" % MaxOut(xList))
else:
    print("No valid numbers entered.")

Error
The summation is 11
The minimum is 1
The maximum is 4


In [ ]:
import numpy as np
import math as m

def Distance(p1,p2):
    d = m.sqrt(np.sum((p1-p2)**2))
    return d

round = 1
y = []

while True:
    x = input("P%d: " %round)
    if x.lower() in "end":
        break
    try:
        x.split()
        for i in x:
            i = float(i)
            y.append(i)

    except ValueError:
        continue


print(y)

[]


: 

In [2]:
import numpy as np

In [ ]:
print(np.array([1,2,3]))

[1 2 3]


: 

In [1]:
import numpy as np

In [23]:
print(np.shape(([1,2,3])))

(3,)


In [24]:
a = np.array([[1,1,2,4], [5,6,7,8], [3,2,1,0], [1,2,3,4]])

size = np.shape(a)
mid = size[0]//2

In [29]:
print(np.diag([1,2,3,4]))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
a = np.argsort([10,2,3,1,20,12,5])
print(a)

0 20
1 2
2 3
3 10
4 5
5 12
6 1

[3 1 2 6 0 5 4]


In [ ]:
from operator import itemgetter

d = {}

while True:
    x = input("Enter student ID and score: ").split()

    id = x[0]
    sc = x[1]

    if id == 'done' and sc =='0':
        break
    else:
        if id in d:
            print("The ID is already recorded!")
        else:
            if len(id) == 4 and id.isnumeric():

                if sc.isnumeric():
                    sc = int(sc)
                    if sc >= 0 and sc <= 100:
                        d[id] = sc
                    else:
                        print("Invalid score")
                else:
                    print("Invalid score")
                        
            else:
                print("Invalid ID format!")
    
def su(x):
    return sum(x)

def prin():
    if d:
        for k,v in sorted(d.items(), key = itemgetter(0)):
            print("%s\t%d" %(k,v))
    else:
        print("> no score is recorded")
    print("There are %d student(s). The average score is %.2f points." %(len(d), su(d.values())/len(d)))

prin()

In [ ]:
from operator import itemgetter
a = {"ce":0,
    "che":0,
    "ec":0,
    "ie":0,
    "me":0}
b = {}

while True:
    x = input("Input: ").split()
    n = x[0]
    if n == "done":
        break
    m,o = x[1],x[2]
    
    o = float(o)
    if o >= 0.00 and o <= 4.00: 
        if m in a.keys():
            a[m] += 1
            b[n] = (o,m)
        else:
            print("ERROR")
    else:
        print("ERROR")

print("----SUMMARY----")
print("ce = %d" %a["ce"])
print("che = %d" %a["che"])
print("ec = %d" %a["ce"])
print("ie = %d" %a["ie"])
print("me = %d" %a["me"])

for i,j,k in sorted(b.items(), key = itemgetter(1), reverse = True):
    print("%s %s %.2f" %(i,k,j))

In [ ]:
print(type((1,2,3,4))) # ("1", "2", ) x,y,z = (1,1,2,3,4,5,6) 

<class 'tuple'>
